name: Build and Publish Platform Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all packages
        run: pnpm -r build

      - name: Verify build artifacts
        run: |
          echo "=== Platform Shell artifacts ==="
          ls -la apps/platform-shell/dist/ || echo "No backend dist"
          ls -la apps/platform-shell/public/ || echo "No frontend dist"
          echo "=== Package artifacts ==="
          ls -la packages/*/dist/ || echo "No package dists"

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate version tag
        id: version
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo "tag=${TIMESTAMP}-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Login to Gitea Container Registry
        run: |
          echo "${{ secrets.GIT_PAT }}" | docker login git.rokkon.com -u "${{ secrets.GIT_USER }}" --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -f apps/platform-shell/Dockerfile \
                       -t git.rokkon.com/io-pipeline/platform-shell:${{ steps.version.outputs.tag }} \
                       -t git.rokkon.com/io-pipeline/platform-shell:latest \
                       .

      - name: Test Docker image
        run: |
          # Clean up any existing test container
          docker rm -f test-shell 2>/dev/null || true

          echo "Starting container (note: backend services may not be available in test environment)"
          docker run -d --name test-shell -p 38106:38106 git.rokkon.com/io-pipeline/platform-shell:latest

          echo "Waiting for frontend to be ready..."
          for i in {1..30}; do
            if curl -f http://localhost:38106/ >/dev/null 2>&1; then
              echo "Frontend is serving HTML!"
              break
            fi
            echo "Attempt $i/30: Frontend not ready yet..."
            sleep 1
          done

          # Verify frontend HTML is served
          echo "Testing frontend HTML response..."
          curl -f http://localhost:38106/ || (echo "Frontend HTML test failed"; docker logs test-shell; exit 1)

          # Check system status endpoint (may return 503 if backend services unavailable, which is OK)
          echo "Testing system status endpoint..."
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:38106/api/system-status)
          if [ "$STATUS_CODE" = "200" ] || [ "$STATUS_CODE" = "503" ]; then
            echo "System status endpoint responding correctly (status: $STATUS_CODE)"
            curl -s http://localhost:38106/api/system-status | head -20
          else
            echo "System status endpoint test failed with status: $STATUS_CODE"
            docker logs test-shell
            exit 1
          fi

          echo "Container tests passed! Frontend serves correctly even when backend services unavailable."

          # Clean up
          docker stop test-shell
          docker rm test-shell

      - name: Push to Gitea Container Registry
        run: |
          docker push git.rokkon.com/io-pipeline/platform-shell:${{ steps.version.outputs.tag }}
          docker push git.rokkon.com/io-pipeline/platform-shell:latest
